// ==================== CALCULATOR DATA ====================

// Calculator data with related search terms
const calculatorData = {
    avgStock: { name: 'Average Stock Price', category: 'Stock & Portfolio', terms: ['average', 'stock', 'price', 'purchase', 'cost basis', 'mean'] },
    requiredQty: { name: 'Required Quantity & Price', category: 'Stock & Portfolio', terms: ['quantity', 'price', 'required', 'shares', 'amount'] },
    dividend: { name: 'Dividend Calculator', category: 'Stock & Portfolio', terms: ['dividend', 'yield', 'income', 'passive', 'earnings'] },
    breakeven: { name: 'Breakeven Point', category: 'Stock & Portfolio', terms: ['breakeven', 'break even', 'profit', 'loss'] },
    sip: { name: 'SIP Calculator', category: 'Investment Planning', terms: ['sip', 'systematic', 'investment', 'plan', 'monthly'] },
    compound: { name: 'Compound Interest', category: 'Investment Planning', terms: ['compound', 'interest', 'growth', 'power', 'multiplier'] },
    investmentGoal: { name: 'Investment Goal', category: 'Investment Planning', terms: ['goal', 'target', 'savings', 'amount', 'future'] },
    costOfDelay: { name: 'Cost of Delay', category: 'Investment Planning', terms: ['delay', 'cost', 'lost', 'opportunity', 'waiting'] },
    fireNumber: { name: 'FIRE Number', category: 'FIRE & Retirement', terms: ['fire', 'financial', 'independence', 'retire', 'number'] },
    yearsToFire: { name: 'Years to FIRE', category: 'FIRE & Retirement', terms: ['years', 'fire', 'timeline', 'when', 'independence'] },
    fatFire: { name: 'FatFIRE Calculator', category: 'FIRE & Retirement', terms: ['fatfire', 'fat', 'luxury', 'premium', 'lifestyle'] },
    leanFire: { name: 'LeanFIRE Calculator', category: 'FIRE & Retirement', terms: ['leanfire', 'lean', 'minimal', 'frugal', 'simple'] },
    retirementAge: { name: 'Retirement Age', category: 'FIRE & Retirement', terms: ['retirement', 'age', 'when', 'retire', 'old'] },
    loanEmi: { name: 'Loan EMI Calculator', category: 'Loans & Borrowing', terms: ['loan', 'emi', 'payment', 'monthly', 'interest'] },
    propertyRoi: { name: 'Property Investment ROI', category: 'Real Estate', terms: ['property', 'roi', 'return', 'investment', 'real estate'] },
    mortgageEmi: { name: 'Mortgage/Home Loan', category: 'Real Estate', terms: ['mortgage', 'home', 'loan', 'house', 'emi'] },
    rule72: { name: 'Rule of 72', category: 'Time & Growth', terms: ['rule', '72', 'double', 'doubling', 'time'] },
    inflation: { name: 'Inflation Calculator', category: 'Time & Growth', terms: ['inflation', 'purchasing', 'power', 'price', 'future'] },
    expenseRatio: { name: 'Expense Ratio Calculator', category: 'Taxes & Fees', terms: ['expense', 'ratio', 'fee', 'fund', 'cost'] },
    emergencyFund: { name: 'Emergency Fund Calculator', category: 'Budgeting & Savings', terms: ['emergency', 'fund', 'savings', 'months', 'buffer'] },
    monthlySavings: { name: 'Monthly Savings Calculator', category: 'Budgeting & Savings', terms: ['savings', 'monthly', 'goal', 'target', 'amount'] },
    budgetAllocator: { name: 'Budget Allocator', category: 'Budgeting & Savings', terms: ['budget', 'allocate', 'allocation', '50/30/20', 'needs'] },
    debtPayoff: { name: 'Debt Payoff Calculator', category: 'Debt Management', terms: ['debt', 'payoff', 'payment', 'timeline', 'interest'] },
    creditCardPayoff: { name: 'Credit Card Payoff Calculator', category: 'Debt Management', terms: ['credit', 'card', 'debt', 'payoff', 'interest'] },
    debtConsolidation: { name: 'Debt Consolidation Calculator', category: 'Debt Management', terms: ['consolidation', 'debt', 'combine', 'merge', 'emi'] },
    cagr: { name: 'CAGR Calculator', category: 'Investment Analysis', terms: ['cagr', 'compound', 'annual', 'growth', 'rate'] },
    roi: { name: 'ROI Calculator', category: 'Investment Analysis', terms: ['roi', 'return', 'investment', 'profit', 'percentage'] },
    drip: { name: 'Dividend Reinvestment (DRIP)', category: 'Investment Analysis', terms: ['drip', 'reinvestment', 'dividend', 'compound', 'growth'] },
    dca: { name: 'Dollar Cost Averaging', category: 'Investment Analysis', terms: ['dca', 'dollar', 'cost', 'averaging', 'monthly'] },
    netWorth: { name: 'Net Worth Calculator', category: 'Wealth Building', terms: ['net', 'worth', 'assets', 'liabilities', 'total'] },
    wealthProjection: { name: 'Wealth Projection', category: 'Wealth Building', terms: ['wealth', 'projection', 'future', 'growth', 'forecast'] },
    millionaireTimeline: { name: 'Millionaire Timeline', category: 'Wealth Building', terms: ['millionaire', 'timeline', 'when', 'crore', 'wealthy'] },
    homeAffordability: { name: 'Home Affordability', category: 'Real Estate (Additional)', terms: ['home', 'affordability', 'price', 'can afford', 'property'] },
    rentVsBuy: { name: 'Rent vs Buy', category: 'Real Estate (Additional)', terms: ['rent', 'buy', 'comparison', 'cost', 'lease'] },
    propertyAppreciation: { name: 'Property Appreciation', category: 'Real Estate (Additional)', terms: ['property', 'appreciation', 'value', 'growth', 'future'] },
    annuityCorpus: { name: 'Annuity/Corpus Calculator', category: 'Retirement (Additional)', terms: ['annuity', 'corpus', 'withdrawal', 'payment', 'income'] },
    retirementIncome: { name: 'Retirement Income Calculator', category: 'Retirement (Additional)', terms: ['retirement', 'income', 'monthly', 'withdrawal', '4%'] },
    inflationCorpus: { name: 'Inflation-Adjusted Corpus', category: 'Retirement (Additional)', terms: ['inflation', 'adjusted', 'corpus', 'future', 'value'] },
    carLoanEmi: { name: 'Car Loan EMI Calculator', category: 'Vehicle Finance', terms: ['car', 'loan', 'emi', 'vehicle', 'payment'] },
    depreciation: { name: 'Depreciation Calculator', category: 'Vehicle Finance', terms: ['depreciation', 'vehicle', 'value', 'car', 'loss'] },
    lifeInsurance: { name: 'Life Insurance Needs', category: 'Insurance', terms: ['insurance', 'life', 'coverage', 'needs', 'protection'] },
    termInsurance: { name: 'Term Insurance Premium', category: 'Insurance', terms: ['term', 'insurance', 'premium', 'cost', 'policy'] },
    educationFund: { name: 'Education Fund Calculator', category: 'Education Planning', terms: ['education', 'fund', 'savings', 'school', 'college'] },
    collegeCost: { name: 'College Cost Projection', category: 'Education Planning', terms: ['college', 'cost', 'education', 'future', 'inflation'] },
    salaryCalculator: { name: 'Salary Calculator', category: 'Income & Earning', terms: ['salary', 'gross', 'net', 'deduction', 'tax'] },
    sideHustleIncome: { name: 'Side Hustle Income', category: 'Income & Earning', terms: ['side', 'hustle', 'income', 'passive', 'extra'] },
    freelanceRate: { name: 'Freelance Rate Calculator', category: 'Income & Earning', terms: ['freelance', 'rate', 'hourly', 'per hour', 'earning'] },
    savingsRate: { name: 'Savings Rate Calculator', category: 'Tracking & Monitoring', terms: ['savings', 'rate', 'percentage', 'how much', 'percent'] },
    goalTracker: { name: 'Goal Tracker', category: 'Tracking & Monitoring', terms: ['goal', 'tracker', 'progress', 'target', 'tracking'] },
    expenseTracker: { name: 'Expense Tracker', category: 'Tracking & Monitoring', terms: ['expense', 'tracker', 'spending', 'monitor', 'track'] },
    loanComparison: { name: 'Loan Comparison', category: 'Loan Comparisons', terms: ['loan', 'comparison', 'compare', 'best', 'options'] },
    paybackPeriod: { name: 'Payback Period Calculator', category: 'Loan Comparisons', terms: ['payback', 'period', 'when', 'paid', 'investment'] },
    earlyPayoff: { name: 'Early Loan Payoff', category: 'Loan Comparisons', terms: ['early', 'payoff', 'extra', 'payment', 'loan'] },
    peRatio: { name: 'P/E Ratio & EPS', category: 'Investment Analysis (Advanced)', terms: ['p/e', 'pe', 'earnings', 'price', 'ratio', 'eps'] },
    dividendGrowth: { name: 'Dividend Growth Calculator', category: 'Investment Analysis (Advanced)', terms: ['dividend', 'growth', 'income', 'future', 'projection'] },
    portfolioRebalancing: { name: 'Portfolio Rebalancing', category: 'Investment Analysis (Advanced)', terms: ['portfolio', 'rebalance', 'allocation', 'asset', 'weightage'] },
    taxLossHarvesting: { name: 'Tax Loss Harvesting', category: 'Tax Planning', terms: ['tax', 'loss', 'harvesting', 'offset', 'capital'] },
    taxBracket: { name: 'Tax Bracket Calculator', category: 'Tax Planning', terms: ['tax', 'bracket', 'rate', 'slab', 'income'] },
    giftTax: { name: 'Gift/Inheritance Tax', category: 'Tax Planning', terms: ['gift', 'inheritance', 'tax', 'estate', 'legacy'] },
    businessProfit: { name: 'Business Profit Calculator', category: 'Business & Freelance', terms: ['business', 'profit', 'revenue', 'cost', 'earnings'] },
    markupMargin: { name: 'Markup vs Margin', category: 'Business & Freelance', terms: ['markup', 'margin', 'price', 'cost', 'profit'] },
    expenseInflation: { name: 'Expense Inflation Calculator', category: 'Lifestyle & Planning', terms: ['expense', 'inflation', 'future', 'cost', 'price'] },
    weddingBudget: { name: 'Wedding Budget Planner', category: 'Lifestyle & Planning', terms: ['wedding', 'budget', 'planner', 'cost', 'event'] },
    vacationBudget: { name: 'Vacation Budget Planner', category: 'Lifestyle & Planning', terms: ['vacation', 'budget', 'trip', 'travel', 'cost'] },
    cryptoROI: { name: 'Crypto Investment ROI', category: 'Crypto & Modern Investing', terms: ['crypto', 'cryptocurrency', 'roi', 'return', 'bitcoin'] },
    cryptoDCA: { name: 'Crypto DCA Calculator', category: 'Crypto & Modern Investing', terms: ['crypto', 'dca', 'dollar cost', 'averaging', 'bitcoin'] },
    bondYield: { name: 'Bond Yield Calculator', category: 'Advanced Financial', terms: ['bond', 'yield', 'interest', 'return', 'fixed income'] },
    npv: { name: 'Net Present Value (NPV)', category: 'Advanced Financial', terms: ['npv', 'net', 'present', 'value', 'project'] },
    irr: { name: 'Internal Rate of Return (IRR)', category: 'Advanced Financial', terms: ['irr', 'internal', 'rate', 'return', 'efficiency'] },
    leaseVsBuy: { name: 'Lease vs Buy Calculator', category: 'Comparison Tools', terms: ['lease', 'buy', 'comparison', 'car', 'equipment'] },
    costOfLiving: { name: 'Cost of Living Adjuster', category: 'Comparison Tools', terms: ['cost', 'living', 'location', 'salary', 'adjust'] },
    rentalYield: { name: 'Rental Yield Calculator', category: 'Real Estate', terms: ['rental', 'yield', 'rent', 'return', 'property'] }
};